name: Fetch Jenkins Build Console Output

on:
  push:
    branches:
      - main

jobs:
  fetch-console-output:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        fetch-depth: 0

    - name: Clone repository
      run: |
        git fetch --prune --unshallow
        git checkout ${{ github.sha }}

    - name: Fetch Jenkins Console Output
      run: |
        # Replace the following values with your Jenkins information
        JENKINS_URL=${{secrets.JENKINS_URL}}
        echo $JENKINS_URL
        
        # JOB_NAME=your-job-name
        # BUILD_NUMBER=your-build-number
        # JENKINS_USER=your-jenkins-username
        # JENKINS_TOKEN=your-jenkins-token

        # Fetch console output using Jenkins REST API
        #CONSOLE_OUTPUT=$(curl -s "${JENKINS_URL}/job/${JOB_NAME}/${BUILD_NUMBER}/consoleText" --user "${JENKINS_USER}:${JENKINS_TOKEN}")

        # Print console output
        #echo "${CONSOLE_OUTPUT}"

