name: Sending Mail

on:
  push:
    branches: ["main"]
        

jobs:
  send-mail:
    runs-on: ubuntu-latest

    steps:
    - name: Failing step
      id: fail
      run: python3 s.py
      
    - name: Running after failed step
      if: failure()
      run: echo "This step is executed because previous step failed"
