name: Sending Mail

on:
  workflow_dispatch:
    inputs:
        version:
          description: Application version
          required: true
          type: string
        release_name:
          description: Release Name
          required: true
          type: string
        
        codeowners:
          description: CodeOwner's Email ID
          required: true
          type: string
        cluster_environment:
          description: Cluster Environment
          required: true
          type: string
        

jobs:
  send-mail:
    runs-on: ubuntu-latest

    steps:
    - name: Notify about beginning of deployment
      uses: dawidd6/action-send-mail@v3
      with:
          server_address: smtp.office365.com
          server_port: 587
          username: noreply@itrnetwork.com
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: Deployment Notification of ${{inputs.release_name}}:${{inputs.version}} - test
          to: ${{inputs.codeowners}}
          from: DevOps Team
          cc: nkashyap@calance.com, nmathur@calance.com
          body: |
            Dear CodeOwner/s,
            
            We are pleased to inform you that a deployment process for ${{ inputs.release_name }} is about to commence.

            Deployment Details:

              Application: ${{inputs.release_name}}
              Version: ${{inputs.version}}
              Environment: ${{inputs.cluster_environment}}
            
            Best Regards,
            DevOps Team 
            
