####
name: Trigger Jenkins Job

on: 
  push:
    branches:
      - "main"

jobs:
  trigger-jenkins-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Create Env
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
      - name: Print env
        run: |
          ls -al
          echo $TEST1
      
          
