####
name: Trigger Jenkins Job

on: 
  push:
    branches:
      - "main"

jobs:
  trigger-jenkins-job:
    runs-on: ubuntu-latest
    environment: dev
    env:
      TEST: ${{secrets.TEST}}
      TEST1: ${{vars.TEST1}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
          
      - name: jfhzd
        run: |
          python main.py
          
