name: Trigger Jenkins Job

on: 
  workflow_dispatch:
      inputs:
        version:
          description: Application version
          required: true
          type: string

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Identifying cluster in which application should be deployed
        id: set_cluster_environment
        uses: actions/github-script@v7
        env:
          version: ${{ github.event.inputs.version }}
        with:
          script: |
            version =  ${{env.version}}
            console.log(version)
            //console.log(${version})
            

