name: Fetch Jenkins Build Console Output

on:
  push:
    branches:
      - main

jobs:
  fetch-console-output:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository (clone the repo for use)
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Fetch Jenkins Console Output
      run: |
        # Replace the following values with your Jenkins information
        JENKINS_URL=${{secrets.JENKINS_URL}}
        echo $JENKINS_URL
        
        # JOB_NAME=your-job-name
        # BUILD_NUMBER=your-build-number
        # JENKINS_USER=your-jenkins-username
        # JENKINS_TOKEN=your-jenkins-token

        # Fetch console output using Jenkins REST API
        #CONSOLE_OUTPUT=$(curl -s "${JENKINS_URL}/job/${JOB_NAME}/${BUILD_NUMBER}/consoleText" --user "${JENKINS_USER}:${JENKINS_TOKEN}")

        # Print console output
        #echo "${CONSOLE_OUTPUT}"

