name: Trigger Jenkins Job

on: 
  workflow_dispatch:
      inputs:
        version:
          description: Application version
          required: true
          type: string

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Identifying cluster in which application should be deployed
        id: set_cluster_environment
        run: |
                echo ${{inputs.version}}
                if [[ ${{inputs.version}} =~ ^v[0-9]+\.[0-9]+\.[0-9]+-rc[0-9]+$ ]]; then
                    cluster_environment="testing"
                
                elif [[ ${{inputs.version}} =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
                    cluster_environment="production"

                else
                    cluster_environment="dev"
                fi

                echo "Cluster Environment: $cluster_environment"
                echo "::set-output name=cluster_environment::$cluster_environment"
            

